### ISSUE TITLE
Templates do not render Markdown

### ISSUE THREAD

**Issue by jonaprieto** [realtimeprojects/mkdocs-ezglossary#6]
As the title says. 

If a template includes something like `[..](...)`, it just renders the same and does not compile to the expected HTML.

**Comment by realtimeprojects** [comment]
Since the page templates are html files, they are not rendered through the markdown rendering engine. Hence, it is not possible to use markdown in the templates.

Currently, I have no intentions to offer markdown templates, since this would make the rendering process quite complex, I doubt that this is even possible at all (unless you have an idea how to implement this).

However, you can use plain html for static links in the template like:

``` html
<a href="[url]">[text]</a>
```

In case you want to link to dynamic content, please provide an example what you are intending to do than I can have a look how you could achieve this.

**Comment by realtimeprojects** [comment]
no response from author, closing for now. Please reopen with more details, if you think, there is still an issue.
